/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.unadm.manejoarchivos;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Formatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Clase principal que crea un archivo con los datos de un empleado, y permite leerlo los datos del archivo
 * Materia: Programacion Orientada a Objetos 3
 * @author Josue Palemon Perez Betanzos
 * @date 04/10/2020 1.0
 */
public class Main extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private String barra = File.separator;
    private String ubicacion  = System.getProperty("user.dir") + barra + "Registros" + barra;
    
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        cardLayout = (CardLayout) panelCards.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelLeft = new javax.swing.JPanel();
        registrarBtn = new javax.swing.JButton();
        buscarBtn = new javax.swing.JButton();
        renombrarBtn = new javax.swing.JButton();
        eliminaBtn = new javax.swing.JButton();
        Modifica = new javax.swing.JButton();
        panelCards = new javax.swing.JPanel();
        pnlRegistro = new javax.swing.JPanel();
        jLblRegistrarEmpleado = new javax.swing.JLabel();
        jLblRfc = new javax.swing.JLabel();
        jTxtRfc = new javax.swing.JTextField();
        jLblNombre = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jTxtNoEmpleado = new javax.swing.JTextField();
        jLblNoEmpleado = new javax.swing.JLabel();
        jBtnRegistrar = new javax.swing.JButton();
        pnlBuscar = new javax.swing.JPanel();
        jLblBuscarEmpleado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtnSeleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtArchivo = new javax.swing.JTextArea();
        pnlModifica = new javax.swing.JPanel();
        jLblModificaArchivo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnModifica = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtAreaModifica = new javax.swing.JTextArea();
        jBtnModificar = new javax.swing.JButton();
        pnlRenombra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtArchivoRenombrar = new javax.swing.JTextField();
        jBtnSelecionArchivo = new javax.swing.JButton();
        jLblNuevoNombre = new javax.swing.JLabel();
        jTxtNuevoNombre = new javax.swing.JTextField();
        jBtnCambiarNombre = new javax.swing.JButton();
        pnlElimina = new javax.swing.JPanel();
        jLblEliminaArchivo = new javax.swing.JLabel();
        jLblSelecionaArchivo = new javax.swing.JLabel();
        jbtnElimina1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrarBtn.setText("Crear");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        buscarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscarBtn.setText("Abrir");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        renombrarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        renombrarBtn.setText("Renombra");
        renombrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renombrarBtnActionPerformed(evt);
            }
        });

        eliminaBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eliminaBtn.setText("Elimina");
        eliminaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaBtnActionPerformed(evt);
            }
        });

        Modifica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Modifica.setText("Modifica");
        Modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(renombrarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Modifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(registrarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modifica)
                .addGap(18, 18, 18)
                .addComponent(buscarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(renombrarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminaBtn)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelLeft);

        panelCards.setLayout(new java.awt.CardLayout());

        jLblRegistrarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblRegistrarEmpleado.setText("Crear Archivo Empleado");

        jLblRfc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblRfc.setText("RFC:");

        jTxtRfc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblNombre.setText("Nombre:");

        jTxtNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTxtNoEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLblNoEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblNoEmpleado.setText("No Empleado:");

        jBtnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                                .addComponent(jLblNoEmpleado)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtNoEmpleado))
                            .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlRegistroLayout.createSequentialGroup()
                                    .addComponent(jLblRfc)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTxtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlRegistroLayout.createSequentialGroup()
                                    .addComponent(jLblNombre)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jBtnRegistrar))))
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLblRegistrarEmpleado)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLblRegistrarEmpleado)
                .addGap(35, 35, 35)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRfc)
                    .addComponent(jTxtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNoEmpleado)
                    .addComponent(jTxtNoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jBtnRegistrar)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jLblRegistrarEmpleado.getAccessibleContext().setAccessibleName("lblTitulo");

        panelCards.add(pnlRegistro, "card2");

        jLblBuscarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblBuscarEmpleado.setText("Abrir Archivo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selecciona el archivo Empleado");

        jBtnSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnSeleccionar.setText("Selecciona");
        jBtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeleccionarActionPerformed(evt);
            }
        });

        jTxtArchivo.setColumns(20);
        jTxtArchivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtArchivo.setRows(5);
        jScrollPane1.setViewportView(jTxtArchivo);

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLblBuscarEmpleado))
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnSeleccionar)))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLblBuscarEmpleado)
                .addGap(28, 28, 28)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBtnSeleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCards.add(pnlBuscar, "card3");

        jLblModificaArchivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblModificaArchivo.setText("Modificar un archivo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Selecciona el archivo que quieres modificar:");

        jbtnModifica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnModifica.setText("Selecciona");
        jbtnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificaActionPerformed(evt);
            }
        });

        jTxtAreaModifica.setColumns(20);
        jTxtAreaModifica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtAreaModifica.setRows(5);
        jScrollPane2.setViewportView(jTxtAreaModifica);

        jBtnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnModificar.setText("Modificar");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModificaLayout = new javax.swing.GroupLayout(pnlModifica);
        pnlModifica.setLayout(pnlModificaLayout);
        pnlModificaLayout.setHorizontalGroup(
            pnlModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificaLayout.createSequentialGroup()
                .addGroup(pnlModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModificaLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLblModificaArchivo))
                    .addGroup(pnlModificaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnModificar)
                            .addGroup(pnlModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlModificaLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtnModifica))))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        pnlModificaLayout.setVerticalGroup(
            pnlModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLblModificaArchivo)
                .addGap(31, 31, 31)
                .addGroup(pnlModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jbtnModifica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnModificar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelCards.add(pnlModifica, "card4");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Renombrar Archivo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Selecciona el archivo que quieres renombrar:");

        jBtnSelecionArchivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSelecionArchivo.setText("Selecciona");
        jBtnSelecionArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelecionArchivoActionPerformed(evt);
            }
        });

        jLblNuevoNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblNuevoNombre.setText("Ingresa el nuevo nombre del archivo:");

        jTxtNuevoNombre.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N

        jBtnCambiarNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnCambiarNombre.setText("Cambiar");
        jBtnCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCambiarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRenombraLayout = new javax.swing.GroupLayout(pnlRenombra);
        pnlRenombra.setLayout(pnlRenombraLayout);
        pnlRenombraLayout.setHorizontalGroup(
            pnlRenombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRenombraLayout.createSequentialGroup()
                .addGroup(pnlRenombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRenombraLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel2))
                    .addGroup(pnlRenombraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlRenombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRenombraLayout.createSequentialGroup()
                                .addComponent(jLblNuevoNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNuevoNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCambiarNombre)
                                .addGap(6, 6, 6))
                            .addGroup(pnlRenombraLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtArchivoRenombrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnSelecionArchivo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRenombraLayout.setVerticalGroup(
            pnlRenombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRenombraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pnlRenombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtArchivoRenombrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSelecionArchivo))
                .addGap(36, 36, 36)
                .addGroup(pnlRenombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNuevoNombre)
                    .addComponent(jTxtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCambiarNombre))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        panelCards.add(pnlRenombra, "card5");

        jLblEliminaArchivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblEliminaArchivo.setText("Eliminar un archivo");

        jLblSelecionaArchivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblSelecionaArchivo.setText("Selecciona el archivo que quieres eliminar:");

        jbtnElimina1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnElimina1.setText("Selecciona");
        jbtnElimina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnElimina1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminaLayout = new javax.swing.GroupLayout(pnlElimina);
        pnlElimina.setLayout(pnlEliminaLayout);
        pnlEliminaLayout.setHorizontalGroup(
            pnlEliminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminaLayout.createSequentialGroup()
                .addGroup(pnlEliminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEliminaLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLblEliminaArchivo))
                    .addGroup(pnlEliminaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLblSelecionaArchivo)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnElimina1)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        pnlEliminaLayout.setVerticalGroup(
            pnlEliminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLblEliminaArchivo)
                .addGap(31, 31, 31)
                .addGroup(pnlEliminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSelecionaArchivo)
                    .addComponent(jbtnElimina1))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        panelCards.add(pnlElimina, "card6");

        jSplitPane1.setRightComponent(panelCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        panelCards.removeAll();
        panelCards.add(pnlRegistro);
        panelCards.repaint();
        panelCards.revalidate();
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        panelCards.removeAll();
        panelCards.add(pnlBuscar);
        panelCards.repaint();
        panelCards.revalidate();
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void jBtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeleccionarActionPerformed
        buscar();
    }//GEN-LAST:event_jBtnSeleccionarActionPerformed

    
    /**
     * Metodo que se encarga de buscar los archivos de los 
     * empleados que se han sido registrados.
     */
    private void buscar(){
        JFileChooser fc = new JFileChooser(); // Es la ventana para la busqueda de archivos
        
        //Pone un directorio actual cuando se abra la ventana de archivos
        fc.setCurrentDirectory(new File(ubicacion));  
        fc.showOpenDialog(null); // abre la ventana de dialogo   
        File archivo = fc.getSelectedFile(); // archivo seleccionado 
        
        try {
            // se crea objeto reader para leer el archivo
            FileReader fr = new FileReader(archivo);
            // buffer del reader para mantener la informacion
            BufferedReader br = new BufferedReader(fr);
            
            String texto = "";
            String linea = "";
            
            // se lee el archivo linea por linea en un ciclo while
            while((linea = br.readLine()) != null){
                // cada linea del archivo se guarda en una cadena
                texto += linea + "\n"; 
            }
            
            jTxtArchivo.setText(texto); // se coloca la informacion de texto en un text area
                    
            // se manda un mensaje que el archivo fue leido correctamente
            JOptionPane.showMessageDialog(null, "Archivo leido correctamente");
        } catch (Exception e) { // si existe un error se manda un mensaje
            JOptionPane.showMessageDialog(null, "Archivo No leido correctamente");
        }
    }
    
    
    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        crear();
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void renombrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renombrarBtnActionPerformed
        panelCards.removeAll();
        panelCards.add(pnlRenombra);
        panelCards.repaint();
        panelCards.revalidate();
    }//GEN-LAST:event_renombrarBtnActionPerformed

    private void eliminaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaBtnActionPerformed
        panelCards.removeAll();
        panelCards.add(pnlElimina);
        panelCards.repaint();
        panelCards.revalidate();
    }//GEN-LAST:event_eliminaBtnActionPerformed

    
    private File selectedFile = new File("");
    
    private void jbtnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificaActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(ubicacion));  
        fc.showOpenDialog(null);
        selectedFile = fc.getSelectedFile();
        
        
        try {
            FileReader fr = new FileReader(selectedFile);
            // buffer del reader para mantener la informacion
            BufferedReader br = new BufferedReader(fr);
            
            String linea = "";
            StringBuilder texto = new StringBuilder();
            
            // se lee el archivo linea por linea en un ciclo while
            while((linea = br.readLine()) != null){
                // cada linea del archivo se guarda en una cadena
                texto.append(linea + "\n"); 
            }
            
            jTxtAreaModifica.setText(texto.toString()); // se coloca la informacion de texto en un text area
                    
            // se manda un mensaje que el archivo fue leido correctamente
            JOptionPane.showMessageDialog(null, "Archivo leido correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Archivo No ha sido leido correctamente");
        }
        
        
    }//GEN-LAST:event_jbtnModificaActionPerformed

    /**
     * Metodo que elimina un archivo seleccionado 
     * @param evt 
     */
    private void jbtnElimina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnElimina1ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(ubicacion));  
        fc.showOpenDialog(null);
        
        File archivo = fc.getSelectedFile();
        
        
        if(archivo.delete()){
            JOptionPane.showMessageDialog(null, "El archivo ha sido borrado exitosamente");
        }else{
            JOptionPane.showMessageDialog(null, "El archivo no puede ser borrado");
        }
    }//GEN-LAST:event_jbtnElimina1ActionPerformed

    
    private File archivoSelected = new File("");
    
    /**
     * Metodo que selecciona un archivo 
     * @param evt 
     */
    private void jBtnSelecionArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecionArchivoActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(ubicacion));  
        fc.showOpenDialog(null);
        
        archivoSelected = fc.getSelectedFile();
        
        jTxtArchivoRenombrar.setText(archivoSelected.getParent() + "\\" + archivoSelected.getName());
        
    }//GEN-LAST:event_jBtnSelecionArchivoActionPerformed

    /**
     * Metodo que cambia el nombre de un archivo 
     * @param evt 
     */
    private void jBtnCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCambiarNombreActionPerformed
        
        String nvo = archivoSelected.getParent() + barra + jTxtNuevoNombre.getText() + ".txt";
        File f2 = new File(nvo);
        
        boolean correcto = archivoSelected.renameTo(f2);
        
        
        if(correcto == true){
            JOptionPane.showMessageDialog(null, "El renombrado ha sido correcto");
            jTxtArchivoRenombrar.setText("");
            jTxtNuevoNombre.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "El renombrado no se ha podido realizar");
        }
        
        
        
    }//GEN-LAST:event_jBtnCambiarNombreActionPerformed

    /**
     * Metodo que se encarga de modificar el contenido de un archivo
     * @param evt 
     */
    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        // get the current file 
        
        String nombreArchivo = selectedFile.getParent() + barra + selectedFile.getName();
        FileWriter writer = null;
        
        try {
            writer = new FileWriter(nombreArchivo);
            BufferedWriter escritor  = new BufferedWriter(writer);
            String texto = jTxtAreaModifica.getText();
            for(int i=0; i<texto.length();i++){
                escritor.write(texto.charAt(i));
            
            }
            
            escritor.close();
            JOptionPane.showMessageDialog(null, "El archivo ha sido modificado");
            jTxtAreaModifica.setText("");
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Archivo No ha sido creado correctamente");
        }
        
        
        
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void ModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaActionPerformed
        panelCards.removeAll();
        panelCards.add(pnlModifica);
        panelCards.repaint();
        panelCards.revalidate();
    }//GEN-LAST:event_ModificaActionPerformed

    
    
    
    /**
     * Metodo que se encarga de crear los empleados registrados
     * y guardarlos en un archivo de texto por empleado
     */
    private void crear(){
        String archivo = jTxtRfc.getText() + ".txt"; // se crea el nombre del archivo
        File creaUbicacion = new File(ubicacion); // crea un objeto File donde se creara el directorio del archivo
        File creaArchivo = new File(ubicacion +  archivo);  // crea el archivo del trabajador que se llenara con la informacion
        
        if(jTxtRfc.getText().equals("")){ // valida que existe un RFC
            JOptionPane.showMessageDialog(rootPane, "No hay RFC");
            
        }else{
            
            try {
                
                if(creaArchivo.exists()){ // si el archivo existe no se crea, ya que cada archivo es unico
                    JOptionPane.showMessageDialog(rootPane, "El registro ya existe");
                }else{
                    creaUbicacion.mkdirs(); // crea la carpeta dentro de la ubicacion del proyecto
                    // Objeto con el que le da formato de lo que se guardara en el archivo
                    Formatter crea = new Formatter(ubicacion + archivo); 
                    
                    // recupera la informacion de la interfaz y la guarda en el archivo
                    // con el formato que se le manda
                    crea.format("%s\r\n%s\r\n%s", "RFC = " + jTxtRfc.getText(),
                            "Nombre = " + jTxtNombre.getText(),
                            "No Empleado = " + jTxtNoEmpleado.getText());
                    
                    crea.close(); // cierra el objeto Formatter
                    // manda un mensaje que el archivo ha sido creado
                    JOptionPane.showMessageDialog(rootPane, "Archivo creado");
                    jTxtRfc.setText("");
                    jTxtNombre.setText("");
                    jTxtNoEmpleado.setText("");
                }
                
            } catch (Exception e) { // si existe una excepcion manda un mensaje
                JOptionPane.showMessageDialog(rootPane, "Archivo NO creado");
            } 
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modifica;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JButton eliminaBtn;
    private javax.swing.JButton jBtnCambiarNombre;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JButton jBtnSeleccionar;
    private javax.swing.JButton jBtnSelecionArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblBuscarEmpleado;
    private javax.swing.JLabel jLblEliminaArchivo;
    private javax.swing.JLabel jLblModificaArchivo;
    private javax.swing.JLabel jLblNoEmpleado;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblNuevoNombre;
    private javax.swing.JLabel jLblRegistrarEmpleado;
    private javax.swing.JLabel jLblRfc;
    private javax.swing.JLabel jLblSelecionaArchivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTxtArchivo;
    private javax.swing.JTextField jTxtArchivoRenombrar;
    private javax.swing.JTextArea jTxtAreaModifica;
    private javax.swing.JTextField jTxtNoEmpleado;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtNuevoNombre;
    private javax.swing.JTextField jTxtRfc;
    private javax.swing.JButton jbtnElimina1;
    private javax.swing.JButton jbtnModifica;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlElimina;
    private javax.swing.JPanel pnlModifica;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JPanel pnlRenombra;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JButton renombrarBtn;
    // End of variables declaration//GEN-END:variables
}
